(load-theme 'solarized-light t)
(set-default-font "Bitstream Vera Sans Mono-10")
(set-fontset-font (frame-parameter nil 'font)
		  'han '("cwTeXHeiBold" . "unicode-bmp"))
(tool-bar-mode -1)
(menu-bar-mode -1)
(nyan-mode 1)
(nyan-start-animation)
