(load (expand-file-name "~/quicklisp/slime-helper.el"))
;(require 'slime)
(require 'slime-autoloads)
(add-hook 'lisp-mode-hook (slime-mode t))
(setq inferior-lisp-program "/usr/bin/sbcl")
(slime-setup '(slime-fancy))
;(setq slime-contribs '(slime-fancy))
